---
name: InventoryMonitor
main: kim\present\inventorymonitor\InventoryMonitor
version: 1.3.2
api: [4.0.0]
author: PresentKim
website: https://github.com/PresentKim/InventoryMonitor-PMMP
description: Monitoring player inventory!

permissions:
  inventorymonitor.cmd:
    description: Open player inventory
    default: op
...