---
name: InventoryMonitor
main: kim\present\inventorymonitor\InventoryMonitor
version: 2.0.0
api: [4.0.0]
author: PresentKim
description: Monitoring player inventory!

permissions:
  inventorymonitor.cmd:
    description: Open player inventory
    default: op
...
